version: '3'
services:
  config-server:
    image: config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: ./config_server
      dockerfile: ../Dockerfile

  service-registry:
    image: service-registry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - config-server.route=config-server:8888
    build:
      context: ./service_registry
      dockerfile: ../Dockerfile

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    environment:
      - service-registry.route=service-registry:8761
      - config-server.route=config-server:8888
    depends_on:
      service-registry:
        condition: service_healthy
    build:
      context: ./gateway
      dockerfile: ../Dockerfile

  rest-api:
    image: rest-api
    environment:
      - service-registry.route=service-registry:8761
      - config-server.route=config-server:8888
    depends_on:
      service-registry:
        condition: service_healthy
    build:
      context: ./restapi
      dockerfile: ../Dockerfile