
spring:
  cloud:
    gateway:
      routes:
        - id: sensor-test-route
#         environment variable if we want to change it
          uri: ${SENSOR_TEST_ROUTE_URI:lb://localhost:8083}
          predicates:
            - Path=/sensors/**
        - id: measurement-test-route
          uri: ${MEASUREMENT_TEST_ROUTE_URI:lb://localhost:8083}
          predicates:
            - Path=/measurements/**
  application:
    name: gateway
#         if we want to change the URI
#         filter:
#           - PrefixPath=/api