spring:
  cloud:
    gateway:
#      routes:
#        - id: sensor-test-route
##         environment variable if we want to change it
#          uri: ${SENSOR_TEST_ROUTE_URI:http://localhost:8083}
#          predicates:
#            - Path=/sensors/**
#        - id: measurement-test-route
#          uri: ${MEASUREMENT_TEST_ROUTE_URI:http://localhost:8083}
#          predicates:
#            - Path=/measurements/**

# Dynamic routes with registry: https://cloud.spring.io/spring-cloud-gateway/2.1.x/multi/multi__configuration.html
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#TODO closer look at load balancing
    loadbalancer:
      ribbon:
        enabled: false

  application:
    name: gateway
#         if we want to change the URI
#         filter:
#           - PrefixPath=/api
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://${service-registry.route}/eureka/
service-registry:
  route: localhost:8761